"""empty message

Revision ID: 42fe499a416e
Revises: a5b8695426fd
Create Date: 2026-02-05 11:20:48.458581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42fe499a416e"
down_revision: Union[str, None] = "a5b8695426fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "proffesion_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("users", "avatar_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "avatar_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("users", "proffesion_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
