"""UserSessionsToken

Revision ID: 4c5c3d27fd7c
Revises: c91a4831032b
Create Date: 2026-02-09 10:27:19.118715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c5c3d27fd7c"
down_revision: Union[str, None] = "c91a4831032b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("likes_post_id_fkey"), "likes", type_="foreignkey")
    op.create_foreign_key(
        None, "likes", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("users_avatar_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "medias", ["avatar_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_avatar_id_fkey"), "users", "medias", ["avatar_id"], ["id"]
    )
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.create_foreign_key(
        op.f("likes_post_id_fkey"), "likes", "posts", ["post_id"], ["id"]
    )
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
