"""empty message

Revision ID: c6a778e23bf5
Revises: 676123d68160
Create Date: 2026-01-29 19:17:18.559891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a778e23bf5'
down_revision: Union[str, None] = '676123d68160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # 1️⃣ NULL bo‘lganlarni hozirgi vaqt bilan to‘ldiramiz
    op.execute(
        "UPDATE comments SET created_at = NOW() WHERE created_at IS NULL ")
    op.execute("UPDATE comments SET updated_at = NOW() WHERE updated_at IS NULL ")

    # 2️⃣ Endi NOT NULL qilish xavfsiz
    op.alter_column(
        'comments',
        'created_at',"updated_at",
        existing_type=sa.DateTime(),
        nullable=False
    )


def pgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('posts', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_table('likes')
    op.drop_table('user_searches')
    op.drop_table('devices')
    # ### end Alembic commands ###
