"""is-deleted user

Revision ID: c91a4831032b
Revises: fa6fccb0233a
Create Date: 2026-02-07 10:48:04.698810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c91a4831032b"
down_revision: Union[str, None] = "fa6fccb0233a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("deleted_email", sa.String(length=100), nullable=True)
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("users", "deleted_email")
    # ### end Alembic commands ###
