"""added_new_features

Revision ID: e877126e478b
Revises: 96b75f9d64ae
Create Date: 2026-01-30 18:59:49.991530

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e877126e478b"
down_revision: Union[str, None] = "96b75f9d64ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
