"""is-deleted user

Revision ID: f7dd0c8b9f89
Revises: 42fe499a416e
Create Date: 2026-02-07 10:33:20.790524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7dd0c8b9f89"
down_revision: Union[str, None] = "42fe499a416e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
