"""is-deleted user

Revision ID: fa6fccb0233a
Revises: f7dd0c8b9f89
Create Date: 2026-02-07 10:37:04.146758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa6fccb0233a"
down_revision: Union[str, None] = "f7dd0c8b9f89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
